[package]
name = "launcher"
version = "0.1.3"
description = "A Tauri App"
authors = ["you"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "1", features = [] }

[dependencies]
tauri = { version = "1", features = [ "api-all"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
anyhow = "1.0.89"
thiserror = "1.0.64"
log = "0.4.22"
env_logger = "0.11.5"
lazy_static = "1.5.0"
discord-rich-presence = "0.2.5"
dotenv = "0.15.0"
copypasta = "0.10.1"
window-shadows = "0.2.2"

[features]
# This feature is used for production builds or when a dev server is not specified, DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]
